<?php
/**
 * @var Zend_View $this
 */
?>
<div id="footer">
	<div class="fb">
		<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fmyeventsvse.cz&amp;send=false&amp;layout=standard&amp;width=250&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=80&amp;appId=150598068321889"
				scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:500px; height:80px;"
				allowTransparency="true"></iframe>
	</div>
</div>

