<div class="wrap">
	<div id="coming-soon-box">
		<div class="left">
			<img src="<?php echo $this->baseUrl(); ?>/img/logo.png" alt="myEvents VŠE"/>
		</div>
		<div class="right">
			<h1>Stránky <strong>myEvents VŠE</strong> se již připravují!</h1>
			<strong class="hi">Ahoj,</strong><br/>

			<p>už se nemůžeš dočkat jako my, až spustíme nový <strong>studentský portál</strong>, kde najdeš <strong>studentské
				akce VŠE?</strong>
				Dej nám ještě nějaký čas, pracujeme na tom.</p>

			<p>Pokud máš jakýkoli dotaz, neváhej nám napsat na <a href="mailto:myeventsvse@gmail.com"><strong>myeventsvse[at]gmail.com</strong></a>
			</p>

			<p>Mezitím než bude nový web hotový, můžeš navštívit naši facebook stránku <a
					href="http://www.facebook.com/myEvents.vse.cz"><strong>myEvents VŠE</strong></a></p>

			<p class="hightlight email">Chceš být informován o spuštění webu? Není problém. Stačí vložit svůj e-mail a
				my Ti dáme včas vědět.</p>

			<form method="post" action="send.php" class="form email">
				<input type="text" class="input" name="email" value="Váš e-mail"/>
				<input type="submit" class="button" value="Informuj mě!"/>
			</form>
			<div class="message">E-mail byl odeslán a uložen!</div>
			<script type="text/javascript">
				if ($.cookie('email_sent') == 'sent') {
					$('.message').css('display', 'block');
				}
			</script>
		</div>
	</div>
</div>
